name: Hypercube
favicon: null
layout_spectrum: 0.95349
typography_spectrum: 0.85542
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff2600'
    - '#000000'
    - '#333333'
    - '#800400'
    - '#808080'
  brandStrength: 0.9446281299460679
  lightness: 0.4375
  saturation: 0
  rhythmicContrast: 0.15519849909469485
purpose: []
